import type { HookTemplate, OverlayPlatform, Platform, PropField } from "./types";

type OverlayDef = {
  slug: string;
  name: string;
  description: string;
  compositionId: string;
  overlayPlatform: OverlayPlatform;
  categories: HookTemplate["categories"];
  platforms: Platform[];
  isPro: boolean;
  popularity: number;
  previewGradient: string;
  defaultProps: Record<string, string | number>;
  props: PropField[];
  exportFrame?: HookTemplate["exportFrame"];
};

const TRANSPARENT_BG = { key: "backgroundColor", label: "Background", type: "color" as const, defaultValue: "transparent" };
const ACCENT = { key: "accentColor", label: "Accent", type: "color" as const, defaultValue: "#6366f1", bindToBrand: "accent" as const };
const THEME = { key: "theme", label: "Theme", type: "text" as const, defaultValue: "dark", maxLength: 10 };

function overlay(
  id: number,
  def: OverlayDef
): HookTemplate {
  return {
    id: String(id),
    slug: def.slug,
    name: def.name,
    description: def.description,
    templateKind: "overlay",
    overlayPlatform: def.overlayPlatform,
    compositionId: def.compositionId,
    durationInFrames: 90,
    fps: 30,
    width: 1080,
    height: 1920,
    orientation: "portrait",
    categories: def.categories,
    visualStyles: ["smooth", "minimal"],
    creatorStyles: ["viral-reels"],
    platforms: def.platforms,
    niches: ["social-media", "creator"],
    isPro: def.isPro,
    isFree: !def.isPro,
    popularity: def.popularity,
    previewGradient: def.previewGradient,
    props: def.props,
    exportFrame: def.exportFrame,
  };
}

const IG_PROPS_BASE = [TRANSPARENT_BG, ACCENT, THEME];
const YT_PROPS = [TRANSPARENT_BG, ACCENT, THEME];

const OVERLAY_DEFINITIONS: OverlayDef[] = [
  // YouTube
  {
    slug: "youtube-like-comment-subscribe",
    name: "YouTube Like Comment Subscribe",
    description: "Animated comment card with like and subscribe CTAs. Classic YouTube engagement overlay.",
    compositionId: "YouTubeEngagement",
    overlayPlatform: "youtube",
    categories: ["engagement-mockup", "subscribe-banner", "comment-popup"],
    platforms: ["youtube"],
    isPro: false,
    popularity: 97,
    previewGradient: "from-red-600 via-zinc-900 to-black",
    defaultProps: { username: "CreatorName", comment: "This video changed my life! 🔥", theme: "dark" },
    props: [
      { key: "username", label: "Username", type: "text", defaultValue: "CreatorName", maxLength: 30 },
      { key: "comment", label: "Comment", type: "text", defaultValue: "This video changed my life! 🔥", maxLength: 100 },
      ...YT_PROPS,
    ],
  },
  {
    slug: "youtube-like-button",
    name: "YouTube Like Button",
    description: "Punchy like counter animation with thumbs up/down UI.",
    compositionId: "YouTubeLikeButton",
    overlayPlatform: "youtube",
    categories: ["engagement-mockup", "social-overlay"],
    platforms: ["youtube"],
    isPro: false,
    popularity: 92,
    previewGradient: "from-zinc-800 via-red-900/40 to-zinc-900",
    defaultProps: { likeCount: "12.4K", theme: "dark" },
    props: [
      { key: "likeCount", label: "Like count", type: "text", defaultValue: "12.4K", maxLength: 15 },
      ...YT_PROPS,
    ],
  },
  {
    slug: "youtube-subscribe-banner",
    name: "YouTube Subscribe Banner",
    description: "Bottom subscribe bar with channel avatar, sub count, and notification bell.",
    compositionId: "YouTubeSubscribeBanner",
    overlayPlatform: "youtube",
    categories: ["subscribe-banner", "profile-banner"],
    platforms: ["youtube"],
    isPro: false,
    popularity: 95,
    previewGradient: "from-red-700 via-zinc-900 to-black",
    defaultProps: { channelName: "Your Channel", subscriberCount: "1.2M", theme: "dark" },
    props: [
      { key: "channelName", label: "Channel name", type: "text", defaultValue: "Your Channel", maxLength: 40 },
      { key: "subscriberCount", label: "Subscribers", type: "text", defaultValue: "1.2M", maxLength: 15 },
      ...YT_PROPS,
    ],
  },
  {
    slug: "youtube-live-badge",
    name: "YouTube Live Badge",
    description: "Live stream indicator with viewer count for streaming content.",
    compositionId: "YouTubeLiveBadge",
    overlayPlatform: "youtube",
    categories: ["notification", "social-overlay"],
    platforms: ["youtube"],
    isPro: true,
    popularity: 88,
    previewGradient: "from-red-600 via-rose-900 to-black",
    defaultProps: { viewerCount: "2,847" },
    props: [
      { key: "viewerCount", label: "Viewer count", type: "text", defaultValue: "2,847", maxLength: 15 },
      TRANSPARENT_BG,
      ACCENT,
    ],
  },
  // Instagram
  {
    slug: "instagram-profile-banner-light",
    name: "Instagram Profile Banner Light",
    description: "Clean light-mode Instagram profile card with avatar and bio.",
    compositionId: "InstagramProfileBanner",
    overlayPlatform: "instagram",
    categories: ["profile-banner", "social-overlay"],
    platforms: ["instagram"],
    isPro: false,
    popularity: 94,
    previewGradient: "from-pink-500 via-purple-500 to-orange-400",
    defaultProps: { username: "yourbrand", displayName: "Your Brand", bio: "Daily tips & reels ✨", theme: "light", layout: "standard" },
    props: [
      { key: "username", label: "Username", type: "text", defaultValue: "yourbrand", maxLength: 30 },
      { key: "displayName", label: "Display name", type: "text", defaultValue: "Your Brand", maxLength: 40 },
      { key: "bio", label: "Bio", type: "text", defaultValue: "Daily tips & reels ✨", maxLength: 80 },
      { key: "layout", label: "Layout", type: "text", defaultValue: "standard", maxLength: 20 },
      ...IG_PROPS_BASE,
    ],
  },
  {
    slug: "instagram-profile-banner-dark",
    name: "Instagram Profile Banner Dark",
    description: "Dark-mode Instagram profile overlay for cinematic edits.",
    compositionId: "InstagramProfileBanner",
    overlayPlatform: "instagram",
    categories: ["profile-banner", "social-overlay"],
    platforms: ["instagram"],
    isPro: true,
    popularity: 90,
    previewGradient: "from-purple-900 via-fuchsia-900 to-black",
    defaultProps: { username: "yourbrand", displayName: "Your Brand", bio: "Creator • Educator • Founder", theme: "dark", layout: "standard" },
    props: [
      { key: "username", label: "Username", type: "text", defaultValue: "yourbrand", maxLength: 30 },
      { key: "displayName", label: "Display name", type: "text", defaultValue: "Your Brand", maxLength: 40 },
      { key: "bio", label: "Bio", type: "text", defaultValue: "Creator • Educator • Founder", maxLength: 80 },
      { key: "layout", label: "Layout", type: "text", defaultValue: "standard", maxLength: 20 },
      ...IG_PROPS_BASE,
    ],
  },
  {
    slug: "instagram-profile-grid",
    name: "Instagram Profile Grid",
    description: "Profile banner with animated photo grid — great for portfolio intros.",
    compositionId: "InstagramProfileBanner",
    overlayPlatform: "instagram",
    categories: ["profile-banner", "social-overlay"],
    platforms: ["instagram"],
    isPro: true,
    popularity: 87,
    previewGradient: "from-violet-600 via-pink-600 to-orange-500",
    defaultProps: { username: "yourbrand", displayName: "Your Brand", bio: "Portfolio highlights", theme: "dark", layout: "grid" },
    props: [
      { key: "username", label: "Username", type: "text", defaultValue: "yourbrand", maxLength: 30 },
      { key: "displayName", label: "Display name", type: "text", defaultValue: "Your Brand", maxLength: 40 },
      { key: "bio", label: "Bio", type: "text", defaultValue: "Portfolio highlights", maxLength: 80 },
      { key: "layout", label: "Layout", type: "text", defaultValue: "grid", maxLength: 20 },
      ...IG_PROPS_BASE,
    ],
  },
  {
    slug: "instagram-heart-notification",
    name: "Instagram Heart Notification",
    description: "Like notification toast — someone liked your post.",
    compositionId: "InstagramHeartNotification",
    overlayPlatform: "instagram",
    categories: ["notification", "engagement-mockup"],
    platforms: ["instagram"],
    isPro: false,
    popularity: 91,
    previewGradient: "from-rose-500 via-pink-600 to-purple-700",
    defaultProps: { username: "fan_account", action: "liked your photo", theme: "dark" },
    props: [
      { key: "username", label: "Username", type: "text", defaultValue: "fan_account", maxLength: 30 },
      { key: "action", label: "Action text", type: "text", defaultValue: "liked your photo", maxLength: 40 },
      ...IG_PROPS_BASE,
    ],
  },
  // TikTok
  {
    slug: "tiktok-comment-popup",
    name: "TikTok Comment Popup",
    description: "Sliding comment bubble with like count — perfect for reaction edits.",
    compositionId: "TikTokCommentPopup",
    overlayPlatform: "tiktok",
    categories: ["comment-popup", "engagement-mockup"],
    platforms: ["tiktok"],
    isPro: false,
    popularity: 93,
    previewGradient: "from-cyan-500 via-pink-500 to-black",
    defaultProps: { username: "@viewer", comment: "Wait this is actually insane 😭", likes: "24.1K", theme: "dark" },
    props: [
      { key: "username", label: "Username", type: "text", defaultValue: "@viewer", maxLength: 30 },
      { key: "comment", label: "Comment", type: "text", defaultValue: "Wait this is actually insane 😭", maxLength: 100 },
      { key: "likes", label: "Likes", type: "text", defaultValue: "24.1K", maxLength: 10 },
      ...IG_PROPS_BASE,
    ],
  },
  // Chat / Messages
  {
    slug: "whatsapp-chat-dark",
    name: "WhatsApp Chat Dark",
    description: "Animated WhatsApp conversation overlay for storytelling edits.",
    compositionId: "ChatOverlay",
    overlayPlatform: "whatsapp",
    categories: ["chat-mockup", "social-overlay"],
    platforms: ["instagram", "tiktok", "youtube"],
    isPro: false,
    popularity: 96,
    previewGradient: "from-emerald-800 via-teal-900 to-black",
    defaultProps: { platform: "whatsapp", contactName: "Client", message: "Can you send the final cut?", reply: "Sending now! 🎬", theme: "dark" },
    props: [
      { key: "platform", label: "Platform", type: "text", defaultValue: "whatsapp", maxLength: 20 },
      { key: "contactName", label: "Contact", type: "text", defaultValue: "Client", maxLength: 30 },
      { key: "message", label: "Incoming message", type: "text", defaultValue: "Can you send the final cut?", maxLength: 120 },
      { key: "reply", label: "Your reply", type: "text", defaultValue: "Sending now! 🎬", maxLength: 120 },
      ...IG_PROPS_BASE,
    ],
  },
  {
    slug: "imessage-notification",
    name: "iMessage Notification",
    description: "iOS-style message notification banner for mobile storytelling.",
    compositionId: "IMessageNotification",
    overlayPlatform: "imessage",
    categories: ["chat-mockup", "notification"],
    platforms: ["instagram", "tiktok"],
    isPro: false,
    popularity: 89,
    previewGradient: "from-zinc-700 via-zinc-900 to-black",
    defaultProps: { sender: "Mom", message: "Did you see my text??", theme: "light" },
    props: [
      { key: "sender", label: "Sender", type: "text", defaultValue: "Mom", maxLength: 30 },
      { key: "message", label: "Message", type: "text", defaultValue: "Did you see my text??", maxLength: 80 },
      ...IG_PROPS_BASE,
    ],
  },
  // Discord / Kick / Twitch
  {
    slug: "discord-call-dark",
    name: "Discord Call Dark",
    description: "Incoming Discord voice call overlay with accept/decline buttons.",
    compositionId: "DiscordCall",
    overlayPlatform: "discord",
    categories: ["social-overlay", "notification"],
    platforms: ["discord", "youtube", "twitch"],
    isPro: true,
    popularity: 86,
    previewGradient: "from-indigo-700 via-violet-900 to-black",
    defaultProps: { serverName: "Creator Hub", channelName: "general", callerName: "Alex", theme: "dark" },
    props: [
      { key: "serverName", label: "Server", type: "text", defaultValue: "Creator Hub", maxLength: 30 },
      { key: "channelName", label: "Channel", type: "text", defaultValue: "general", maxLength: 30 },
      { key: "callerName", label: "Caller", type: "text", defaultValue: "Alex", maxLength: 30 },
      ...IG_PROPS_BASE,
    ],
  },
  {
    slug: "kick-profile",
    name: "Kick Profile",
    description: "Kick streamer profile card with follower count and live badge.",
    compositionId: "KickProfile",
    overlayPlatform: "kick",
    categories: ["profile-banner", "social-overlay"],
    platforms: ["kick", "youtube"],
    isPro: false,
    popularity: 84,
    previewGradient: "from-lime-400 via-green-900 to-black",
    defaultProps: { username: "StreamerName", followerCount: "48.2K", isLive: "yes" },
    props: [
      { key: "username", label: "Username", type: "text", defaultValue: "StreamerName", maxLength: 30 },
      { key: "followerCount", label: "Followers", type: "text", defaultValue: "48.2K", maxLength: 15 },
      { key: "isLive", label: "Show LIVE badge", type: "text", defaultValue: "yes", maxLength: 5 },
      TRANSPARENT_BG,
      { key: "accentColor", label: "Accent", type: "color", defaultValue: "#53FC18", bindToBrand: "accent" },
    ],
  },
  {
    slug: "twitch-follow-alert",
    name: "Twitch Follow Alert",
    description: "Twitch-style new follower notification toast.",
    compositionId: "FollowNotification",
    overlayPlatform: "twitch",
    categories: ["notification", "engagement-mockup"],
    platforms: ["twitch"],
    isPro: false,
    popularity: 85,
    previewGradient: "from-purple-600 via-violet-900 to-black",
    defaultProps: { platform: "twitch", username: "NewViewer", action: "just followed!" },
    props: [
      { key: "platform", label: "Platform", type: "text", defaultValue: "twitch", maxLength: 20 },
      { key: "username", label: "Username", type: "text", defaultValue: "NewViewer", maxLength: 30 },
      { key: "action", label: "Action", type: "text", defaultValue: "just followed!", maxLength: 40 },
      TRANSPARENT_BG,
      ACCENT,
    ],
  },
  {
    slug: "twitter-follow-alert",
    name: "X Follow Alert",
    description: "X/Twitter new follower notification overlay.",
    compositionId: "FollowNotification",
    overlayPlatform: "twitter",
    categories: ["notification", "engagement-mockup"],
    platforms: ["twitter"],
    isPro: false,
    popularity: 83,
    previewGradient: "from-sky-500 via-blue-900 to-black",
    defaultProps: { platform: "twitter", username: "@newfan", action: "started following you" },
    props: [
      { key: "platform", label: "Platform", type: "text", defaultValue: "twitter", maxLength: 20 },
      { key: "username", label: "Username", type: "text", defaultValue: "@newfan", maxLength: 30 },
      { key: "action", label: "Action", type: "text", defaultValue: "started following you", maxLength: 40 },
      TRANSPARENT_BG,
      ACCENT,
    ],
  },
  {
    slug: "reddit-award-notification",
    name: "Reddit Award Notification",
    description: "Reddit-style engagement notification for community content.",
    compositionId: "FollowNotification",
    overlayPlatform: "reddit",
    categories: ["notification", "engagement-mockup"],
    platforms: ["reddit"],
    isPro: true,
    popularity: 78,
    previewGradient: "from-orange-500 via-red-900 to-black",
    defaultProps: { platform: "reddit", username: "u/HelpfulUser", action: "gave you an award 🏆" },
    props: [
      { key: "platform", label: "Platform", type: "text", defaultValue: "reddit", maxLength: 20 },
      { key: "username", label: "Username", type: "text", defaultValue: "u/HelpfulUser", maxLength: 30 },
      { key: "action", label: "Action", type: "text", defaultValue: "gave you an award 🏆", maxLength: 40 },
      TRANSPARENT_BG,
      ACCENT,
    ],
  },
  {
    slug: "threads-follow-alert",
    name: "Threads Follow Alert",
    description: "Threads follow notification for Meta ecosystem creators.",
    compositionId: "FollowNotification",
    overlayPlatform: "threads",
    categories: ["notification", "engagement-mockup"],
    platforms: ["threads", "instagram"],
    isPro: false,
    popularity: 80,
    previewGradient: "from-zinc-600 via-zinc-900 to-black",
    defaultProps: { platform: "threads", username: "creator_fan", action: "followed you" },
    props: [
      { key: "platform", label: "Platform", type: "text", defaultValue: "threads", maxLength: 20 },
      { key: "username", label: "Username", type: "text", defaultValue: "creator_fan", maxLength: 30 },
      { key: "action", label: "Action", type: "text", defaultValue: "followed you", maxLength: 40 },
      TRANSPARENT_BG,
      ACCENT,
    ],
  },
  // Logo / Utility
  {
    slug: "logo-animation",
    name: "Logo Animation",
    description: "Brand logo reveal with shine sweep and tagline fade-in.",
    compositionId: "LogoReveal",
    overlayPlatform: "generic",
    categories: ["logo-animation", "social-overlay"],
    platforms: ["youtube", "instagram", "tiktok", "linkedin"],
    isPro: false,
    popularity: 90,
    previewGradient: "from-violet-600 via-indigo-600 to-cyan-500",
    defaultProps: { brandName: "YourBrand", tagline: "Create. Share. Grow." },
    props: [
      { key: "brandName", label: "Brand name", type: "text", defaultValue: "YourBrand", maxLength: 30 },
      { key: "tagline", label: "Tagline", type: "text", defaultValue: "Create. Share. Grow.", maxLength: 50 },
      TRANSPARENT_BG,
      ACCENT,
    ],
  },
  {
    slug: "browser-address-bar",
    name: "Browser Address Bar",
    description: "Animated browser URL bar with typing effect for tutorial content.",
    compositionId: "BrowserAddressBar",
    overlayPlatform: "browser",
    categories: ["search-bar", "ui-animation"],
    platforms: ["youtube", "linkedin"],
    isPro: false,
    popularity: 82,
    previewGradient: "from-slate-500 via-zinc-700 to-zinc-900",
    defaultProps: { url: "https://yoursite.com", searchQuery: "best-video-hooks" },
    props: [
      { key: "url", label: "URL", type: "text", defaultValue: "https://yoursite.com", maxLength: 60 },
      { key: "searchQuery", label: "Typed query", type: "text", defaultValue: "best-video-hooks", maxLength: 50 },
      TRANSPARENT_BG,
      ACCENT,
    ],
  },
  {
    slug: "google-search-bar",
    name: "Google Search Bar",
    description: "Typing search bar animation — great for 'how I found this' hooks.",
    compositionId: "SearchBarTyping",
    overlayPlatform: "browser",
    categories: ["search-bar", "ui-animation"],
    platforms: ["youtube", "tiktok", "instagram"],
    isPro: false,
    popularity: 88,
    previewGradient: "from-blue-500 via-white/20 to-zinc-800",
    defaultProps: { query: "how to go viral on tiktok", platform: "google" },
    props: [
      { key: "query", label: "Search query", type: "text", defaultValue: "how to go viral on tiktok", maxLength: 80 },
      { key: "platform", label: "Style", type: "text", defaultValue: "google", maxLength: 20 },
      TRANSPARENT_BG,
      ACCENT,
    ],
  },
];

export const OVERLAY_CATALOG: HookTemplate[] = OVERLAY_DEFINITIONS.map((def, i) =>
  overlay(i + 100, def)
);

export const OVERLAY_PLATFORM_LABELS: Record<OverlayPlatform, string> = {
  youtube: "YouTube",
  instagram: "Instagram",
  tiktok: "TikTok",
  twitch: "Twitch",
  kick: "Kick",
  discord: "Discord",
  twitter: "X (Twitter)",
  threads: "Threads",
  reddit: "Reddit",
  whatsapp: "WhatsApp",
  imessage: "iMessage",
  browser: "Browser",
  generic: "Logo / Brand",
};
